# Generated by Django 5.2.6 on 2025-09-30 10:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('gameId', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
